language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pajamaguy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pajamaguy/react-test npm test

after_success:
  - docker build -t pajamaguy/multi-client ./client
  - docker build -t pajamaguy/multi-nginx ./nginx
  - docker build -t pajamaguy/multi-server ./server
  - docker build -t pajamaguy/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push pajamaguy/multi-client
  - docker push pajamaguy/multi-nginx
  - docker push pajamaguy/multi-server
  - docker push pajamaguy/multi-worker
